server:
  port: 8000

eureka:
  instance:
    hostname: his.ccm.ink
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
ribbon:
  eureka:
    enabled: true

spring:
  application:
    name: eurka-server