server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
ribbon:
  eureka:
    enabled: true

spring:
  application:
    name: eurka-server