spring:
  application:
    name: eureka-consumer


eureka:
  instance:
    hostname: his.ccm.ink
  client:
    fetchRegistry: true
    registerWithEureka: true
    enabled: true
    serviceUrl:
      defaultZone: http://129.211.61.153:8000/eureka
server:
  port: 8010
